### ISSUE TITLE
Missing secure acces to mqtt server

### ISSUE THREAD

**Issue by arno58** [JeroenvO/homeassistant-cz20-badge#1]
I have change your code to connect a mqtt server using user and password
After changing the code you have to add MQTT_user and MQTT_password to setings

Old code:

                                                      'MQTT_discovery_prefix': 'homeassistant',
                                                      'on_press_color': '0xffffff'})
SERVER_IP = settings['MQTT_server_ip']
DEVICE_NAME = settings['MQTT_device_name'].strip('/')
PREFIX = settings['MQTT_discovery_prefix'].strip('/')

New code:
                                                      'MQTT_discovery_prefix': 'homeassistant',
                                                      'MQTT_user': "gebruiker",
                                                      'MQTT_password': "geheim",
                                                      'on_press_color': '0xffffff'})
SERVER_IP = settings['MQTT_server_ip']
DEVICE_NAME = settings['MQTT_device_name'].strip('/')
PREFIX = settings['MQTT_discovery_prefix'].strip('/')
USER = settings['MQTT_user'].strip('/')
PASSWORD = settings['MQTT_password'].strip('/')

Old code:

c = MQTTClient(UUID, SERVER_IP)

New code:

c = MQTTClient(UUID, SERVER_IP,user= USER, password= PASSWORD)

**Comment by JeroenvO** [comment]
nice addition.
We should add a default of None and i don't think the `strip('/')` should be there

**Comment by JeroenvO** [comment]
fixed.
