### ISSUE TITLE
off topic flash memory problems

### ISSUE THREAD

**Issue by arno58** [JeroenvO/homeassistant-cz20-badge#5]
I am having problems with saving files i changed and cant install you app from internet.
I think i have damaged flash memory or the file index.
File names are created but with zero size.
I would like to reflash the badge but i have found no information about a procedure for this badge only one bin file.

**Comment by JeroenvO** [comment]
This does not belong here. Check:
* https://wiki.badge.team/Main_Page
* https://docs.badge.team/
* https://t.me/joinchat/AMG-ZhQQ9cE1KAAbQozy5Q

**Comment by arno58** [comment]
Thank You, wil have a look there.

Op zo 2 mei 2021 21:27 schreef JeroenvO ***@***.***>:
